(define-foreign canvas-save-n0 "canvas" "saveN0" (ref extern) -> none)
(define-foreign canvas-restore-n0 "canvas" "restoreN0" (ref extern) -> none)
(define-foreign canvas-reset-n0 "canvas" "resetN0" (ref extern) -> none)
(define-foreign canvas-is-context-lost-n0 "canvas" "isContextLostN0" (ref extern) -> i32)
(define-foreign canvas-scale-n2 "canvas" "scaleN2" (ref extern) f32 f32 -> none)
(define-foreign canvas-rotate-n1 "canvas" "rotateN1" (ref extern) f32 -> none)
(define-foreign canvas-translate-n2 "canvas" "translateN2" (ref extern) f32 f32 -> none)
(define-foreign canvas-transform-n6 "canvas" "transformN6" (ref extern) f32 f32 f32 f32 f32 f32 -> none)
(define-foreign canvas-set-transform-n6 "canvas" "setTransformN6" (ref extern) f32 f32 f32 f32 f32 f32 -> none)
(define-foreign canvas-set-transform-n0 "canvas" "setTransformN0" (ref extern) -> none)
(define-foreign canvas-reset-transform-n0 "canvas" "resetTransformN0" (ref extern) -> none)
(define-foreign canvas-global-alpha "canvas" "globalAlpha" (ref extern) f32 -> none)
(define-foreign canvas-global-composite-operation "canvas" "globalCompositeOperation" (ref extern) (ref string) -> none)
(define-foreign canvas-image-smoothing-enabled "canvas" "imageSmoothingEnabled" (ref extern) i32 -> none)
(define-foreign canvas-image-smoothing-quality "canvas" "imageSmoothingQuality" (ref extern) (ref extern) -> none)
(define-foreign canvas-stroke-style "canvas" "strokeStyle" (ref extern) (ref string) -> none)
(define-foreign canvas-fill-style "canvas" "fillStyle" (ref extern) (ref string) -> none)
(define-foreign canvas-create-linear-gradient-n4 "canvas" "createLinearGradientN4" (ref extern) f32 f32 f32 f32 -> (ref extern))
(define-foreign canvas-create-radial-gradient-n6 "canvas" "createRadialGradientN6" (ref extern) f32 f32 f32 f32 f32 f32 -> (ref extern))
(define-foreign canvas-create-conic-gradient-n3 "canvas" "createConicGradientN3" (ref extern) f32 f32 f32 -> (ref extern))
(define-foreign canvas-shadow-offset-x "canvas" "shadowOffsetX" (ref extern) f32 -> none)
(define-foreign canvas-shadow-offset-y "canvas" "shadowOffsetY" (ref extern) f32 -> none)
(define-foreign canvas-shadow-blur "canvas" "shadowBlur" (ref extern) f32 -> none)
(define-foreign canvas-shadow-color "canvas" "shadowColor" (ref extern) (ref string) -> none)
(define-foreign canvas-filter "canvas" "filter" (ref extern) (ref string) -> none)
(define-foreign canvas-clear-rect-n4 "canvas" "clearRectN4" (ref extern) f32 f32 f32 f32 -> none)
(define-foreign canvas-fill-rect-n4 "canvas" "fillRectN4" (ref extern) f32 f32 f32 f32 -> none)
(define-foreign canvas-stroke-rect-n4 "canvas" "strokeRectN4" (ref extern) f32 f32 f32 f32 -> none)
(define-foreign canvas-begin-path-n0 "canvas" "beginPathN0" (ref extern) -> none)
(define-foreign canvas-fill-n0 "canvas" "fillN0" (ref extern) -> none)
(define-foreign canvas-fill-n1 "canvas" "fillN1" (ref extern) (ref extern) -> none)
(define-foreign canvas-stroke-n0 "canvas" "strokeN0" (ref extern) -> none)
(define-foreign canvas-stroke-n1 "canvas" "strokeN1" (ref extern) (ref extern) -> none)
(define-foreign canvas-clip-n0 "canvas" "clipN0" (ref extern) -> none)
(define-foreign canvas-clip-n1 "canvas" "clipN1" (ref extern) (ref extern) -> none)
(define-foreign canvas-is-point-in-path-n2 "canvas" "isPointInPathN2" (ref extern) f32 f32 -> i32)
(define-foreign canvas-is-point-in-path-n3 "canvas" "isPointInPathN3" (ref extern) (ref extern) f32 f32 -> i32)
(define-foreign canvas-is-point-in-stroke-n2 "canvas" "isPointInStrokeN2" (ref extern) f32 f32 -> i32)
(define-foreign canvas-is-point-in-stroke-n3 "canvas" "isPointInStrokeN3" (ref extern) (ref extern) f32 f32 -> i32)
(define-foreign canvas-draw-focus-if-needed-n1 "canvas" "drawFocusIfNeededN1" (ref extern) (ref extern) -> none)
(define-foreign canvas-draw-focus-if-needed-n2 "canvas" "drawFocusIfNeededN2" (ref extern) (ref extern) (ref extern) -> none)
(define-foreign canvas-scroll-path-into-view-n0 "canvas" "scrollPathIntoViewN0" (ref extern) -> none)
(define-foreign canvas-scroll-path-into-view-n1 "canvas" "scrollPathIntoViewN1" (ref extern) (ref extern) -> none)
(define-foreign canvas-fill-text-n3 "canvas" "fillTextN3" (ref extern) (ref string) f32 f32 -> none)
(define-foreign canvas-stroke-text-n3 "canvas" "strokeTextN3" (ref extern) (ref string) f32 f32 -> none)
(define-foreign canvas-measure-text-n1 "canvas" "measureTextN1" (ref extern) (ref string) -> (ref extern))
(define-foreign canvas-draw-image-n3 "canvas" "drawImageN3" (ref extern) (ref extern) f32 f32 -> none)
(define-foreign canvas-draw-image-n5 "canvas" "drawImageN5" (ref extern) (ref extern) f32 f32 f32 f32 -> none)
(define-foreign canvas-draw-image-n9 "canvas" "drawImageN9" (ref extern) (ref extern) f32 f32 f32 f32 f32 f32 f32 f32 -> none)
(define-foreign canvas-create-image-data-n2 "canvas" "createImageDataN2" (ref extern) i32 i32 -> (ref extern))
(define-foreign canvas-create-image-data-n1 "canvas" "createImageDataN1" (ref extern) (ref extern) -> (ref extern))
(define-foreign canvas-get-image-data-n4 "canvas" "getImageDataN4" (ref extern) i32 i32 i32 i32 -> (ref extern))
(define-foreign canvas-put-image-data-n3 "canvas" "putImageDataN3" (ref extern) (ref extern) i32 i32 -> none)
(define-foreign canvas-put-image-data-n7 "canvas" "putImageDataN7" (ref extern) (ref extern) i32 i32 i32 i32 i32 i32 -> none)
(define-foreign canvas-line-width "canvas" "lineWidth" (ref extern) f32 -> none)
(define-foreign canvas-line-cap "canvas" "lineCap" (ref extern) (ref extern) -> none)
(define-foreign canvas-line-join "canvas" "lineJoin" (ref extern) (ref extern) -> none)
(define-foreign canvas-miter-limit "canvas" "miterLimit" (ref extern) f32 -> none)
(define-foreign canvas-set-line-dash-n1 "canvas" "setLineDashN1" (ref extern) (ref extern) -> none)
(define-foreign canvas-line-dash-offset "canvas" "lineDashOffset" (ref extern) f32 -> none)
(define-foreign canvas-font "canvas" "font" (ref extern) (ref string) -> none)
(define-foreign canvas-text-align "canvas" "textAlign" (ref extern) (ref string) -> none)
(define-foreign canvas-text-baseline "canvas" "textBaseline" (ref extern) (ref string) -> none)
(define-foreign canvas-direction "canvas" "direction" (ref extern) (ref string) -> none)
(define-foreign canvas-letter-spacing "canvas" "letterSpacing" (ref extern) (ref string) -> none)
(define-foreign canvas-font-kerning "canvas" "fontKerning" (ref extern) (ref string) -> none)
(define-foreign canvas-font-stretch "canvas" "fontStretch" (ref extern) (ref string) -> none)
(define-foreign canvas-font-variant-caps "canvas" "fontVariantCaps" (ref extern) (ref string) -> none)
(define-foreign canvas-text-rendering "canvas" "textRendering" (ref extern) (ref string) -> none)
(define-foreign canvas-word-spacing "canvas" "wordSpacing" (ref extern) (ref string) -> none)
(define-foreign canvas-close-path-n0 "canvas" "closePathN0" (ref extern) -> none)
(define-foreign canvas-move-to-n2 "canvas" "moveToN2" (ref extern) f32 f32 -> none)
(define-foreign canvas-line-to-n2 "canvas" "lineToN2" (ref extern) f32 f32 -> none)
(define-foreign canvas-quadratic-curve-to-n4 "canvas" "quadraticCurveToN4" (ref extern) f32 f32 f32 f32 -> none)
(define-foreign canvas-bezier-curve-to-n6 "canvas" "bezierCurveToN6" (ref extern) f32 f32 f32 f32 f32 f32 -> none)
(define-foreign canvas-arc-to-n5 "canvas" "arcToN5" (ref extern) f32 f32 f32 f32 f32 -> none)
(define-foreign canvas-rect-n4 "canvas" "rectN4" (ref extern) f32 f32 f32 f32 -> none)
(define-foreign canvas-round-rect-n4 "canvas" "roundRectN4" (ref extern) f32 f32 f32 f32 -> none)
(define-foreign canvas-arc-n5 "canvas" "arcN5" (ref extern) f32 f32 f32 f32 f32 -> none)
(define-foreign canvas-ellipse-n7 "canvas" "ellipseN7" (ref extern) f32 f32 f32 f32 f32 f32 f32 -> none)
